// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using KKday.PMS.B2S.Models.Shared;
//
//    var scmBaseModel = ScmModel.FromJson(jsonString);

namespace KKday.PMS.B2S.Models.Shared
{
    using Newtonsoft.Json;

    public partial class RSModel
    {
        [JsonProperty("result")]
        public string result { get; set; } 

        [JsonProperty("msg")] 
        public string msg { get; set; } 

    }
}
