// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using KKday.PMS.B2S.Models.Shared;
//
//    var scmBaseModel = ScmModel.FromJson(jsonString);

namespace KKday.PMS.B2S.Models.Shared
{
    using Newtonsoft.Json;

    public partial class ScmBaseModel
    {
        [JsonProperty("apiKey")]
        public string ApiKey { get; set; }

        [JsonProperty("userOid")]
        public long UserOid { get; set; }

        [JsonProperty("ver")]
        public string Ver { get; set; }

        [JsonProperty("locale")]
        public string Locale { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("ipaddress")]
        public string Ipaddress { get; set; }
    }
}
