//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.0.30319.1 自動產生。
// 
namespace ezfly.dpkg.crslib {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Request_GetAv {
        
        private CrsSystemOption crsSystemField;
        
        private string rule_TypeField;
        
        private string remarkField;
        
        private Itinerary[] itineraryField;
        
        private bool isPassMMCField;
        
        /// <remarks/>
        public CrsSystemOption CrsSystem {
            get {
                return this.crsSystemField;
            }
            set {
                this.crsSystemField = value;
            }
        }
        
        /// <remarks/>
        public string Rule_Type {
            get {
                return this.rule_TypeField;
            }
            set {
                this.rule_TypeField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Itinerary")]
        public Itinerary[] Itinerary {
            get {
                return this.itineraryField;
            }
            set {
                this.itineraryField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPassMMC {
            get {
                return this.isPassMMCField;
            }
            set {
                this.isPassMMCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute("CrsSystem", Namespace="", IsNullable=false)]
    public enum CrsSystemOption {
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        B7,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        AL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Itinerary {
        
        private Segment[] segmentField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Segment")]
        public Segment[] Segment {
            get {
                return this.segmentField;
            }
            set {
                this.segmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Segment {
        
        private string segNoField;
        
        private string tripFlagField;
        
        private string departureDateField;
        
        private string departureTimeField;
        
        private string departureAirportField;
        
        private string arrivalDateField;
        
        private string arrivalTimeField;
        
        private string arrivalAirportField;
        
        private string airlineField;
        
        private string flightNumberField;
        
        private string equipmentField;
        
        private System.Nullable<bool> isStayField;
        
        private string bookingClassField;
        
        private System.Nullable<int> bookingSeatCountField;
        
        private string statusField;
        
        private string ticketNoField;
        
        private string fareBasisField;
        
        private Public_Fare_Price public_Fare_PriceField;
        
        private Net_Fare_Price net_Fare_PriceField;
        
        /// <remarks/>
        public string SegNo {
            get {
                return this.segNoField;
            }
            set {
                this.segNoField = value;
            }
        }
        
        /// <remarks/>
        public string TripFlag {
            get {
                return this.tripFlagField;
            }
            set {
                this.tripFlagField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureDate {
            get {
                return this.departureDateField;
            }
            set {
                this.departureDateField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureTime {
            get {
                return this.departureTimeField;
            }
            set {
                this.departureTimeField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureAirport {
            get {
                return this.departureAirportField;
            }
            set {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                this.arrivalDateField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                this.arrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        public string Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
            }
        }
        
        /// <remarks/>
        public string FlightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                this.flightNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsStay {
            get {
                return this.isStayField;
            }
            set {
                this.isStayField = value;
            }
        }
        
        /// <remarks/>
        public string BookingClass {
            get {
                return this.bookingClassField;
            }
            set {
                this.bookingClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BookingSeatCount {
            get {
                return this.bookingSeatCountField;
            }
            set {
                this.bookingSeatCountField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string TicketNo {
            get {
                return this.ticketNoField;
            }
            set {
                this.ticketNoField = value;
            }
        }
        
        /// <remarks/>
        public string FareBasis {
            get {
                return this.fareBasisField;
            }
            set {
                this.fareBasisField = value;
            }
        }
        
        /// <remarks/>
        public Public_Fare_Price Public_Fare_Price {
            get {
                return this.public_Fare_PriceField;
            }
            set {
                this.public_Fare_PriceField = value;
            }
        }
        
        /// <remarks/>
        public Net_Fare_Price Net_Fare_Price {
            get {
                return this.net_Fare_PriceField;
            }
            set {
                this.net_Fare_PriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Public_Fare_Price {
        
        private int aDULTField;
        
        private int aGEDField;
        
        private int cHILDField;
        
        /// <remarks/>
        public int ADULT {
            get {
                return this.aDULTField;
            }
            set {
                this.aDULTField = value;
            }
        }
        
        /// <remarks/>
        public int AGED {
            get {
                return this.aGEDField;
            }
            set {
                this.aGEDField = value;
            }
        }
        
        /// <remarks/>
        public int CHILD {
            get {
                return this.cHILDField;
            }
            set {
                this.cHILDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Net_Fare_Price {
        
        private int aDULTField;
        
        private int aGEDField;
        
        private int cHILDField;
        
        /// <remarks/>
        public int ADULT {
            get {
                return this.aDULTField;
            }
            set {
                this.aDULTField = value;
            }
        }
        
        /// <remarks/>
        public int AGED {
            get {
                return this.aGEDField;
            }
            set {
                this.aGEDField = value;
            }
        }
        
        /// <remarks/>
        public int CHILD {
            get {
                return this.cHILDField;
            }
            set {
                this.cHILDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Response_GetAv {
        
        private ResponseSummary responseSummaryField;
        
        private AvItinerary[] avItineraryField;
        
        private string remarkField;
        
        /// <remarks/>
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvItinerary")]
        public AvItinerary[] AvItinerary {
            get {
                return this.avItineraryField;
            }
            set {
                this.avItineraryField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ResponseSummary {
        
        private object errorCodeField;
        
        private object errorDescField;
        
        private bool isSuccessField;
        
        /// <remarks/>
        public object ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public object ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AvItinerary {
        
        private Segments[] segmentsField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Segments")]
        public Segments[] Segments {
            get {
                return this.segmentsField;
            }
            set {
                this.segmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Segments {
        
        private Segment[] segmentField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Segment")]
        public Segment[] Segment {
            get {
                return this.segmentField;
            }
            set {
                this.segmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Request_CreatePNR {
        
        private CrsSystemOption crsSystemField;
        
        private string orderNoField;
        
        private string validateAirlineField;
        
        private AskSegment[] askSegmentField;
        
        private Traveler[] travelerField;
        
        private Contact contactField;
        
        private Sales salesField;
        
        private RoomType roomTypeField;
        
        private string remarkField;
        
        /// <remarks/>
        public CrsSystemOption CrsSystem {
            get {
                return this.crsSystemField;
            }
            set {
                this.crsSystemField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string ValidateAirline {
            get {
                return this.validateAirlineField;
            }
            set {
                this.validateAirlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AskSegment")]
        public AskSegment[] AskSegment {
            get {
                return this.askSegmentField;
            }
            set {
                this.askSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Traveler")]
        public Traveler[] Traveler {
            get {
                return this.travelerField;
            }
            set {
                this.travelerField = value;
            }
        }
        
        /// <remarks/>
        public Contact Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public Sales Sales {
            get {
                return this.salesField;
            }
            set {
                this.salesField = value;
            }
        }
        
        /// <remarks/>
        public RoomType RoomType {
            get {
                return this.roomTypeField;
            }
            set {
                this.roomTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AskSegment {
        
        private string segNoField;
        
        private string tripFlagField;
        
        private string departureDateField;
        
        private string departureTimeField;
        
        private string departureAirportField;
        
        private string arrivalDateField;
        
        private string arrivalTimeField;
        
        private string arrivalAirportField;
        
        private string airlineField;
        
        private string flightNumberField;
        
        private string equipmentField;
        
        private System.Nullable<bool> isStayField;
        
        private string bookingClassField;
        
        private System.Nullable<int> bookingSeatCountField;
        
        private string statusField;
        
        private string fareBasisField;
        
        private string listSeqnoField;
        
        /// <remarks/>
        public string SegNo {
            get {
                return this.segNoField;
            }
            set {
                this.segNoField = value;
            }
        }
        
        /// <remarks/>
        public string TripFlag {
            get {
                return this.tripFlagField;
            }
            set {
                this.tripFlagField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureDate {
            get {
                return this.departureDateField;
            }
            set {
                this.departureDateField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureTime {
            get {
                return this.departureTimeField;
            }
            set {
                this.departureTimeField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureAirport {
            get {
                return this.departureAirportField;
            }
            set {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                this.arrivalDateField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                this.arrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        public string Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
            }
        }
        
        /// <remarks/>
        public string FlightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                this.flightNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsStay {
            get {
                return this.isStayField;
            }
            set {
                this.isStayField = value;
            }
        }
        
        /// <remarks/>
        public string BookingClass {
            get {
                return this.bookingClassField;
            }
            set {
                this.bookingClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BookingSeatCount {
            get {
                return this.bookingSeatCountField;
            }
            set {
                this.bookingSeatCountField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string FareBasis {
            get {
                return this.fareBasisField;
            }
            set {
                this.fareBasisField = value;
            }
        }
        
        /// <remarks/>
        public string ListSeqno {
            get {
                return this.listSeqnoField;
            }
            set {
                this.listSeqnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Traveler {
        
        private object lST_SEQNOField;
        
        private string cUS_SEQNOField;
        
        private string pIDField;
        
        private string nameLastField;
        
        private string nameFirstField;
        
        private System.Nullable<PersonType> typeField;
        
        private System.Nullable<PersonTitle> titleField;
        
        private System.Nullable<PersonSex> sexField;
        
        private string birthdayField;
        
        private System.Nullable<int> ageYearField;
        
        private System.Nullable<int> ageMonthField;
        
        private string nation_TypeField;
        
        public Traveler() {
            this.cUS_SEQNOField = "";
        }
        
        /// <remarks/>
        public object LST_SEQNO {
            get {
                return this.lST_SEQNOField;
            }
            set {
                this.lST_SEQNOField = value;
            }
        }
        
        /// <remarks/>
        public string CUS_SEQNO {
            get {
                return this.cUS_SEQNOField;
            }
            set {
                this.cUS_SEQNOField = value;
            }
        }
        
        /// <remarks/>
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        public string NameLast {
            get {
                return this.nameLastField;
            }
            set {
                this.nameLastField = value;
            }
        }
        
        /// <remarks/>
        public string NameFirst {
            get {
                return this.nameFirstField;
            }
            set {
                this.nameFirstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<PersonType> Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<PersonTitle> Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<PersonSex> Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AgeYear {
            get {
                return this.ageYearField;
            }
            set {
                this.ageYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AgeMonth {
            get {
                return this.ageMonthField;
            }
            set {
                this.ageMonthField = value;
            }
        }
        
        /// <remarks/>
        public string Nation_Type {
            get {
                return this.nation_TypeField;
            }
            set {
                this.nation_TypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum PersonType {
        
        /// <remarks/>
        ADT,
        
        /// <remarks/>
        CHD,
        
        /// <remarks/>
        INF,
        
        /// <remarks/>
        ELD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum PersonTitle {
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MSTR,
        
        /// <remarks/>
        MISS,
        
        /// <remarks/>
        MRS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum PersonSex {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Contact {
        
        private string nameLastField;
        
        private string nameFirstField;
        
        private PersonTitle typeField;
        
        private string mobileField;
        
        private string phoneField;
        
        private string eMailField;
        
        /// <remarks/>
        public string NameLast {
            get {
                return this.nameLastField;
            }
            set {
                this.nameLastField = value;
            }
        }
        
        /// <remarks/>
        public string NameFirst {
            get {
                return this.nameFirstField;
            }
            set {
                this.nameFirstField = value;
            }
        }
        
        /// <remarks/>
        public PersonTitle Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Sales {
        
        private string salesNoField;
        
        private string nameField;
        
        private string cityField;
        
        private string phoneField;
        
        private string phoneExtField;
        
        /// <remarks/>
        public string SalesNo {
            get {
                return this.salesNoField;
            }
            set {
                this.salesNoField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneExt {
            get {
                return this.phoneExtField;
            }
            set {
                this.phoneExtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum RoomType {
        
        /// <remarks/>
        SGLB,
        
        /// <remarks/>
        DBLB,
        
        /// <remarks/>
        TRPB,
        
        /// <remarks/>
        QUAB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Response_CreatePNR {
        
        private ResponseSummary responseSummaryField;
        
        private string pNRField;
        
        private string remarkField;
        
        /// <remarks/>
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
        
        /// <remarks/>
        public string PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Request_DisplayPNR {
        
        private CrsSystemOption crsSystemField;
        
        private string pNRField;
        
        private string remarkField;
        
        /// <remarks/>
        public CrsSystemOption CrsSystem {
            get {
                return this.crsSystemField;
            }
            set {
                this.crsSystemField = value;
            }
        }
        
        /// <remarks/>
        public string PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Response_DisplayPNR {
        
        private ResponseSummary responseSummaryField;
        
        private Segment[] segmentField;
        
        private Traveler[] travelerField;
        
        private string remarkField;
        
        /// <remarks/>
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Segment")]
        public Segment[] Segment {
            get {
                return this.segmentField;
            }
            set {
                this.segmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Traveler")]
        public Traveler[] Traveler {
            get {
                return this.travelerField;
            }
            set {
                this.travelerField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Request_CancelETKT {
        
        private CrsSystemOption crsSystemField;
        
        private CancelType cMDField;
        
        private string pNRField;
        
        private ETKTNOs[] eTKTNOsField;
        
        private string remarkField;
        
        /// <remarks/>
        public CrsSystemOption CrsSystem {
            get {
                return this.crsSystemField;
            }
            set {
                this.crsSystemField = value;
            }
        }
        
        /// <remarks/>
        public CancelType CMD {
            get {
                return this.cMDField;
            }
            set {
                this.cMDField = value;
            }
        }
        
        /// <remarks/>
        public string PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ETKTNOs")]
        public ETKTNOs[] ETKTNOs {
            get {
                return this.eTKTNOsField;
            }
            set {
                this.eTKTNOsField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum CancelType {
        
        /// <remarks/>
        VOID,
        
        /// <remarks/>
        RFND,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ETKTNOs {
        
        private string eTKTNOField;
        
        private string[] textField;
        
        /// <remarks/>
        public string ETKTNO {
            get {
                return this.eTKTNOField;
            }
            set {
                this.eTKTNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Response_CancelETKT {
        
        private ResponseSummary responseSummaryField;
        
        private string pNRField;
        
        private Segments[] segmentsField;
        
        private string remarkField;
        
        /// <remarks/>
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
        
        /// <remarks/>
        public string PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Segments")]
        public Segments[] Segments {
            get {
                return this.segmentsField;
            }
            set {
                this.segmentsField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Request_CancelPNR {
        
        private CrsSystemOption crsSystemField;
        
        private string pNRField;
        
        private string remarkField;
        
        /// <remarks/>
        public CrsSystemOption CrsSystem {
            get {
                return this.crsSystemField;
            }
            set {
                this.crsSystemField = value;
            }
        }
        
        /// <remarks/>
        public string PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Response_CancelPNR {
        
        private ResponseSummary responseSummaryField;
        
        private object pNRField;
        
        private object remarkField;
        
        /// <remarks/>
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
        
        /// <remarks/>
        public object PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        public object Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Request_OpenTkt {
        
        private CrsSystemOption crsSystemField;
        
        private string validateAirlineField;
        
        private string pNRField;
        
        private string fareNBRField;
        
        private int publishFareField;
        
        private int netFareField;
        
        private string orderNoField;
        
        private string departureAirportField;
        
        private string arrivalAirportField;
        
        private EtktSegmentB7[] etktSegmentB7Field;
        
        private string oPEN_TKT_OPField;
        
        private string orderNo1Field;
        
        private string remarkField;
        
        private Contact contactField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CrsSystemOption CrsSystem {
            get {
                return this.crsSystemField;
            }
            set {
                this.crsSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ValidateAirline {
            get {
                return this.validateAirlineField;
            }
            set {
                this.validateAirlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FareNBR {
            get {
                return this.fareNBRField;
            }
            set {
                this.fareNBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PublishFare {
            get {
                return this.publishFareField;
            }
            set {
                this.publishFareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int NetFare {
            get {
                return this.netFareField;
            }
            set {
                this.netFareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DepartureAirport {
            get {
                return this.departureAirportField;
            }
            set {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ArrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EtktSegmentB7", Order=9)]
        public EtktSegmentB7[] EtktSegmentB7 {
            get {
                return this.etktSegmentB7Field;
            }
            set {
                this.etktSegmentB7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OPEN_TKT_OP {
            get {
                return this.oPEN_TKT_OPField;
            }
            set {
                this.oPEN_TKT_OPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderNo", Order=11)]
        public string OrderNo1 {
            get {
                return this.orderNo1Field;
            }
            set {
                this.orderNo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public Contact Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class EtktSegmentB7 {
        
        private string lST_SEQNOField;
        
        private string cUS_SEQNOField;
        
        private string pNR_CUS_SEQField;
        
        private string cUS_NAMEField;
        
        private string fareNBRField;
        
        private int publishFareField;
        
        private int netFareField;
        
        private TicketType ticketTypeField;
        
        public EtktSegmentB7() {
            this.cUS_SEQNOField = "";
        }
        
        /// <remarks/>
        public string LST_SEQNO {
            get {
                return this.lST_SEQNOField;
            }
            set {
                this.lST_SEQNOField = value;
            }
        }
        
        /// <remarks/>
        public string CUS_SEQNO {
            get {
                return this.cUS_SEQNOField;
            }
            set {
                this.cUS_SEQNOField = value;
            }
        }
        
        /// <remarks/>
        public string PNR_CUS_SEQ {
            get {
                return this.pNR_CUS_SEQField;
            }
            set {
                this.pNR_CUS_SEQField = value;
            }
        }
        
        /// <remarks/>
        public string CUS_NAME {
            get {
                return this.cUS_NAMEField;
            }
            set {
                this.cUS_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string FareNBR {
            get {
                return this.fareNBRField;
            }
            set {
                this.fareNBRField = value;
            }
        }
        
        /// <remarks/>
        public int PublishFare {
            get {
                return this.publishFareField;
            }
            set {
                this.publishFareField = value;
            }
        }
        
        /// <remarks/>
        public int NetFare {
            get {
                return this.netFareField;
            }
            set {
                this.netFareField = value;
            }
        }
        
        /// <remarks/>
        public TicketType TicketType {
            get {
                return this.ticketTypeField;
            }
            set {
                this.ticketTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum TicketType {
        
        /// <remarks/>
        YPKG,
        
        /// <remarks/>
        YPKGCD,
        
        /// <remarks/>
        YPKGCH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Response_OpenTkt {
        
        private ResponseSummary responseSummaryField;
        
        private object remarkField;
        
        /// <remarks/>
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
        
        /// <remarks/>
        public object Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Request_GetEtkt {
        
        private CrsSystemOption crsSystemField;
        
        private string pNRField;
        
        private string remarkField;
        
        /// <remarks/>
        public CrsSystemOption CrsSystem {
            get {
                return this.crsSystemField;
            }
            set {
                this.crsSystemField = value;
            }
        }
        
        /// <remarks/>
        public string PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Response_GetEtkt {
        
        private ResponseSummary responseSummaryField;
        
        private object strXMLField;
        
        private object remarkField;
        
        /// <remarks/>
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
        
        /// <remarks/>
        public object StrXML {
            get {
                return this.strXMLField;
            }
            set {
                this.strXMLField = value;
            }
        }
        
        /// <remarks/>
        public object Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ETicket {
        
        private string passengerField;
        
        private string nameRefField;
        
        private string customerNoField;
        
        private CrsSystemOption crsSystemField;
        
        private string issueDateField;
        
        private string issuingAirlineField;
        
        private string tourCodeField;
        
        private Segment[] segmentField;
        
        private string formOfPaymentField;
        
        private string endorsementRestrictionField;
        
        private string fareCurrencyField;
        
        private string fareField;
        
        private string netFareCurrencyField;
        
        private System.Nullable<double> netFareAmtField;
        
        /// <remarks/>
        public string Passenger {
            get {
                return this.passengerField;
            }
            set {
                this.passengerField = value;
            }
        }
        
        /// <remarks/>
        public string NameRef {
            get {
                return this.nameRefField;
            }
            set {
                this.nameRefField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNo {
            get {
                return this.customerNoField;
            }
            set {
                this.customerNoField = value;
            }
        }
        
        /// <remarks/>
        public CrsSystemOption CrsSystem {
            get {
                return this.crsSystemField;
            }
            set {
                this.crsSystemField = value;
            }
        }
        
        /// <remarks/>
        public string IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public string IssuingAirline {
            get {
                return this.issuingAirlineField;
            }
            set {
                this.issuingAirlineField = value;
            }
        }
        
        /// <remarks/>
        public string TourCode {
            get {
                return this.tourCodeField;
            }
            set {
                this.tourCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Segment")]
        public Segment[] Segment {
            get {
                return this.segmentField;
            }
            set {
                this.segmentField = value;
            }
        }
        
        /// <remarks/>
        public string FormOfPayment {
            get {
                return this.formOfPaymentField;
            }
            set {
                this.formOfPaymentField = value;
            }
        }
        
        /// <remarks/>
        public string EndorsementRestriction {
            get {
                return this.endorsementRestrictionField;
            }
            set {
                this.endorsementRestrictionField = value;
            }
        }
        
        /// <remarks/>
        public string FareCurrency {
            get {
                return this.fareCurrencyField;
            }
            set {
                this.fareCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string Fare {
            get {
                return this.fareField;
            }
            set {
                this.fareField = value;
            }
        }
        
        /// <remarks/>
        public string NetFareCurrency {
            get {
                return this.netFareCurrencyField;
            }
            set {
                this.netFareCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> NetFareAmt {
            get {
                return this.netFareAmtField;
            }
            set {
                this.netFareAmtField = value;
            }
        }
    }
}
