// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using KKday.PMS.B2S.Models.Package. SCMPackageCalendarModel;
//
//    var scmPackageCalendarModel = ScmPackageCalendarModel.FromJson(jsonString);

namespace KKday.PMS.B2S.Models.Package.SCMPackageCalendarModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using KKday.PMS.B2S.Models.Shared;

    public partial class ScmPackageCalendarModel : ScmBaseModel
    {
        [JsonProperty("json")]
        public Json Json { get; set; }
    }

    public partial class Json
    {
        [JsonProperty("packageOid")]
        public long PackageOid { get; set; }

        [JsonProperty("prodOid")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ProdOid { get; set; }

        [JsonProperty("weekDays")]
        public string WeekDays { get; set; }

        [JsonProperty("startDt")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long StartDt { get; set; }

        [JsonProperty("endDt")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long EndDt { get; set; }

        [JsonProperty("supplierOid")]
        public long SupplierOid { get; set; }

        [JsonProperty("supplierUserUuid")]
        public Guid SupplierUserUuid { get; set; }

        [JsonProperty("deviceId")]
        public string DeviceId { get; set; }

        [JsonProperty("tokenKey")]
        public string TokenKey { get; set; }
    }

    public partial class ScmPackageCalendarModel
    {
        public static ScmPackageCalendarModel FromJson(string json) => JsonConvert.DeserializeObject<ScmPackageCalendarModel>(json, KKday.PMS.B2S.Models.Package. SCMPackageCalendarModel.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ScmPackageCalendarModel self) => JsonConvert.SerializeObject(self, KKday.PMS.B2S.Models.Package. SCMPackageCalendarModel.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
