//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKday.Web.B2D.BE.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KKday.Web.B2D.BE.Resources.Text.en-US", typeof(Text_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CURR_AUD {
            get {
                return ResourceManager.GetString("CURR_AUD", resourceCulture);
            }
        }
        
        internal static string CURR_CAD {
            get {
                return ResourceManager.GetString("CURR_CAD", resourceCulture);
            }
        }
        
        internal static string CURR_CNY {
            get {
                return ResourceManager.GetString("CURR_CNY", resourceCulture);
            }
        }
        
        internal static string CURR_EUR {
            get {
                return ResourceManager.GetString("CURR_EUR", resourceCulture);
            }
        }
        
        internal static string CURR_GBP {
            get {
                return ResourceManager.GetString("CURR_GBP", resourceCulture);
            }
        }
        
        internal static string CURR_HKD {
            get {
                return ResourceManager.GetString("CURR_HKD", resourceCulture);
            }
        }
        
        internal static string CURR_IDR {
            get {
                return ResourceManager.GetString("CURR_IDR", resourceCulture);
            }
        }
        
        internal static string CURR_JPY {
            get {
                return ResourceManager.GetString("CURR_JPY", resourceCulture);
            }
        }
        
        internal static string CURR_KRW {
            get {
                return ResourceManager.GetString("CURR_KRW", resourceCulture);
            }
        }
        
        internal static string CURR_MYR {
            get {
                return ResourceManager.GetString("CURR_MYR", resourceCulture);
            }
        }
        
        internal static string CURR_NZD {
            get {
                return ResourceManager.GetString("CURR_NZD", resourceCulture);
            }
        }
        
        internal static string CURR_PHP {
            get {
                return ResourceManager.GetString("CURR_PHP", resourceCulture);
            }
        }
        
        internal static string CURR_SGD {
            get {
                return ResourceManager.GetString("CURR_SGD", resourceCulture);
            }
        }
        
        internal static string CURR_THB {
            get {
                return ResourceManager.GetString("CURR_THB", resourceCulture);
            }
        }
        
        internal static string CURR_TWD {
            get {
                return ResourceManager.GetString("CURR_TWD", resourceCulture);
            }
        }
        
        internal static string CURR_USD {
            get {
                return ResourceManager.GetString("CURR_USD", resourceCulture);
            }
        }
        
        internal static string CURR_VND {
            get {
                return ResourceManager.GetString("CURR_VND", resourceCulture);
            }
        }
        
        internal static string KKday_CopyRight {
            get {
                return ResourceManager.GetString("KKday_CopyRight", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        internal static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        internal static string Repricing {
            get {
                return ResourceManager.GetString("Repricing", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        internal static string Data_Not_Found {
            get {
                return ResourceManager.GetString("Data_Not_Found", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string ProductNo {
            get {
                return ResourceManager.GetString("ProductNo", resourceCulture);
            }
        }
        
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        internal static string ContactTel {
            get {
                return ResourceManager.GetString("ContactTel", resourceCulture);
            }
        }
        
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        internal static string UpdateOK {
            get {
                return ResourceManager.GetString("UpdateOK", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        internal static string CompanyProfile {
            get {
                return ResourceManager.GetString("CompanyProfile", resourceCulture);
            }
        }
        
        internal static string GenderTitle {
            get {
                return ResourceManager.GetString("GenderTitle", resourceCulture);
            }
        }
        
        internal static string NameLast {
            get {
                return ResourceManager.GetString("NameLast", resourceCulture);
            }
        }
        
        internal static string NameFirst {
            get {
                return ResourceManager.GetString("NameFirst", resourceCulture);
            }
        }
        
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        internal static string CountryANDTelCode {
            get {
                return ResourceManager.GetString("CountryANDTelCode", resourceCulture);
            }
        }
        
        internal static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        internal static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string PasswordAgain {
            get {
                return ResourceManager.GetString("PasswordAgain", resourceCulture);
            }
        }
        
        internal static string CannotChange {
            get {
                return ResourceManager.GetString("CannotChange", resourceCulture);
            }
        }
        
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        internal static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        internal static string OnlyTaiwan {
            get {
                return ResourceManager.GetString("OnlyTaiwan", resourceCulture);
            }
        }
        
        internal static string CacheTime {
            get {
                return ResourceManager.GetString("CacheTime", resourceCulture);
            }
        }
        
        internal static string Search_Name {
            get {
                return ResourceManager.GetString("Search_Name", resourceCulture);
            }
        }
        
        internal static string Search_Name_Last {
            get {
                return ResourceManager.GetString("Search_Name_Last", resourceCulture);
            }
        }
        
        internal static string Search_Name_First {
            get {
                return ResourceManager.GetString("Search_Name_First", resourceCulture);
            }
        }
        
        internal static string Search_Email {
            get {
                return ResourceManager.GetString("Search_Email", resourceCulture);
            }
        }
        
        internal static string Search_Tel {
            get {
                return ResourceManager.GetString("Search_Tel", resourceCulture);
            }
        }
        
        internal static string Search_JobTitle {
            get {
                return ResourceManager.GetString("Search_JobTitle", resourceCulture);
            }
        }
        
        internal static string Search_Department {
            get {
                return ResourceManager.GetString("Search_Department", resourceCulture);
            }
        }
        
        internal static string Title_Distributor {
            get {
                return ResourceManager.GetString("Title_Distributor", resourceCulture);
            }
        }
        
        internal static string Title_VoucherApply {
            get {
                return ResourceManager.GetString("Title_VoucherApply", resourceCulture);
            }
        }
        
        internal static string Title_Order {
            get {
                return ResourceManager.GetString("Title_Order", resourceCulture);
            }
        }
        
        internal static string Title_B2dAccount {
            get {
                return ResourceManager.GetString("Title_B2dAccount", resourceCulture);
            }
        }
        
        internal static string Title_B2dApiAccount {
            get {
                return ResourceManager.GetString("Title_B2dApiAccount", resourceCulture);
            }
        }
        
        internal static string Title_PriceBlacklist {
            get {
                return ResourceManager.GetString("Title_PriceBlacklist", resourceCulture);
            }
        }
        
        internal static string Title_PriceSetting {
            get {
                return ResourceManager.GetString("Title_PriceSetting", resourceCulture);
            }
        }
        
        internal static string Title_GoBooking {
            get {
                return ResourceManager.GetString("Title_GoBooking", resourceCulture);
            }
        }
        
        internal static string Title_MyProfile {
            get {
                return ResourceManager.GetString("Title_MyProfile", resourceCulture);
            }
        }
        
        internal static string Title_AddVoucher {
            get {
                return ResourceManager.GetString("Title_AddVoucher", resourceCulture);
            }
        }
        
        internal static string Title_MyOrder {
            get {
                return ResourceManager.GetString("Title_MyOrder", resourceCulture);
            }
        }
        
        internal static string Title_ChangePassword {
            get {
                return ResourceManager.GetString("Title_ChangePassword", resourceCulture);
            }
        }
        
        internal static string Title_WebUser {
            get {
                return ResourceManager.GetString("Title_WebUser", resourceCulture);
            }
        }
        
        internal static string Title_ApiUser {
            get {
                return ResourceManager.GetString("Title_ApiUser", resourceCulture);
            }
        }
        
        internal static string Title_WebUserProfile {
            get {
                return ResourceManager.GetString("Title_WebUserProfile", resourceCulture);
            }
        }
        
        internal static string Title_ApiUserProfile {
            get {
                return ResourceManager.GetString("Title_ApiUserProfile", resourceCulture);
            }
        }
        
        internal static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        internal static string UserRole_00 {
            get {
                return ResourceManager.GetString("UserRole_00", resourceCulture);
            }
        }
        
        internal static string UserRole_01 {
            get {
                return ResourceManager.GetString("UserRole_01", resourceCulture);
            }
        }
        
        internal static string Company_Name {
            get {
                return ResourceManager.GetString("Company_Name", resourceCulture);
            }
        }
        
        internal static string Company_Invoice {
            get {
                return ResourceManager.GetString("Company_Invoice", resourceCulture);
            }
        }
        
        internal static string Company_Url {
            get {
                return ResourceManager.GetString("Company_Url", resourceCulture);
            }
        }
        
        internal static string Company_Address {
            get {
                return ResourceManager.GetString("Company_Address", resourceCulture);
            }
        }
        
        internal static string Company_PromotionSetting {
            get {
                return ResourceManager.GetString("Company_PromotionSetting", resourceCulture);
            }
        }
        
        internal static string Companyloggero {
            get {
                return ResourceManager.GetString("Companyloggero", resourceCulture);
            }
        }
        
        internal static string Company_Progress_00 {
            get {
                return ResourceManager.GetString("Company_Progress_00", resourceCulture);
            }
        }
        
        internal static string Company_Progress_01 {
            get {
                return ResourceManager.GetString("Company_Progress_01", resourceCulture);
            }
        }
        
        internal static string Company_Progress_02 {
            get {
                return ResourceManager.GetString("Company_Progress_02", resourceCulture);
            }
        }
        
        internal static string Company_Progress_03 {
            get {
                return ResourceManager.GetString("Company_Progress_03", resourceCulture);
            }
        }
        
        internal static string Company_Progress_04 {
            get {
                return ResourceManager.GetString("Company_Progress_04", resourceCulture);
            }
        }
        
        internal static string Company_Progress_NA {
            get {
                return ResourceManager.GetString("Company_Progress_NA", resourceCulture);
            }
        }
        
        internal static string Company_Status_00 {
            get {
                return ResourceManager.GetString("Company_Status_00", resourceCulture);
            }
        }
        
        internal static string Company_Status_01 {
            get {
                return ResourceManager.GetString("Company_Status_01", resourceCulture);
            }
        }
        
        internal static string Company_Status_02 {
            get {
                return ResourceManager.GetString("Company_Status_02", resourceCulture);
            }
        }
        
        internal static string Company_Status_03 {
            get {
                return ResourceManager.GetString("Company_Status_03", resourceCulture);
            }
        }
        
        internal static string Company_Status_04 {
            get {
                return ResourceManager.GetString("Company_Status_04", resourceCulture);
            }
        }
        
        internal static string FixedPrice {
            get {
                return ResourceManager.GetString("FixedPrice", resourceCulture);
            }
        }
        
        internal static string FixedPriceSetting {
            get {
                return ResourceManager.GetString("FixedPriceSetting", resourceCulture);
            }
        }
    }
}
