//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKday.Web.B2D.BE.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KKday.Web.B2D.BE.Resources.Text.en-US", typeof(Text_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string KKday_CopyRight {
            get {
                return ResourceManager.GetString("KKday_CopyRight", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Company_Title {
            get {
                return ResourceManager.GetString("Company_Title", resourceCulture);
            }
        }
        
        internal static string Company_Search_Name {
            get {
                return ResourceManager.GetString("Company_Search_Name", resourceCulture);
            }
        }
        
        internal static string Company_Search_Country {
            get {
                return ResourceManager.GetString("Company_Search_Country", resourceCulture);
            }
        }
        
        internal static string Company_Search_Status {
            get {
                return ResourceManager.GetString("Company_Search_Status", resourceCulture);
            }
        }
        
        internal static string Company_Search_Sorting {
            get {
                return ResourceManager.GetString("Company_Search_Sorting", resourceCulture);
            }
        }
        
        internal static string Company_Search_Button {
            get {
                return ResourceManager.GetString("Company_Search_Button", resourceCulture);
            }
        }
        
        internal static string Company_List_Col_Name {
            get {
                return ResourceManager.GetString("Company_List_Col_Name", resourceCulture);
            }
        }
        
        internal static string Company_List_Col_Promo {
            get {
                return ResourceManager.GetString("Company_List_Col_Promo", resourceCulture);
            }
        }
    }
}
